"""Initial catalog for a fresh database: users and objects only."""

from __future__ import annotations

import uuid

SEED_PASSWORD = "password"
SEED_LOGISTICS_ID = uuid.UUID("44444444-4444-4444-4444-444444444444")

USERS = [
    {
        "id": uuid.UUID("11111111-1111-1111-1111-111111111111"),
        "username": "commercial",
        "email": "commercial@company.ru",
        "full_name": "Иванов Иван",
        "role": "commercial",
        "department": "Коммерческий отдел",
    },
    {
        "id": uuid.UUID("22222222-2222-2222-2222-222222222222"),
        "username": "pp",
        "email": "pp@company.ru",
        "full_name": "Петров Петр",
        "role": "pp",
        "department": "Планирование производства",
    },
    {
        "id": uuid.UUID("33333333-3333-3333-3333-333333333333"),
        "username": "economist",
        "email": "economist@company.ru",
        "full_name": "Сидоров Сидор",
        "role": "economist",
        "department": "Экономический отдел",
    },
    {
        "id": uuid.UUID("44444444-4444-4444-4444-444444444444"),
        "username": "logistics",
        "email": "logistics@company.ru",
        "full_name": "Кузнецов Кузьма",
        "role": "logistics",
        "department": "Логистика",
    },
    {
        "id": uuid.UUID("55555555-5555-5555-5555-555555555555"),
        "username": "guest",
        "email": "guest@company.ru",
        "full_name": "Смирнов Гость",
        "role": "guest",
        "department": None,
    },
]

OBJECTS = [
    {
        "code": 2420,
        "name": "ТПП Волгоград",
        "city": "Волгоград",
        "region": "Волгоградская область",
        "type": "plant",
        "erp_plant_code": 2420,
        "erp_warehouse_code": "F001",
        "loading_point": "2420",
    },
    {
        "code": 2421,
        "name": "ТПП Пермь",
        "city": "Пермь",
        "region": "Пермский край",
        "type": "plant",
        "erp_plant_code": 2421,
        "erp_warehouse_code": "F001",
        "loading_point": "2421",
    },
    {
        "code": 2422,
        "name": "ТПП Торжок",
        "city": "Торжок",
        "region": "Тверская область",
        "type": "plant",
        "erp_plant_code": 2422,
        "erp_warehouse_code": "F001",
        "loading_point": "2422",
    },
    {
        "code": 2423,
        "name": "Тюменский филиал",
        "city": "Богандинский",
        "region": "Тюменская область",
        "type": "plant",
        "erp_plant_code": 2423,
        "erp_warehouse_code": "F001",
        "loading_point": "2423",
    },
    {
        "code": 2401002,
        "name": "ЛогЛаб Санкт-Петербург",
        "city": "Санкт-Петербург",
        "region": "Ленинградская область",
        "type": "warehouse",
        "erp_plant_code": 2401,
        "erp_warehouse_code": "F002",
        "loading_point": "2R02",
    },
    {
        "code": 2401004,
        "name": "ЛогЛаб Нижний Новгород",
        "city": "Дзержинск",
        "region": "Нижегородская область",
        "type": "warehouse",
        "erp_plant_code": 2401,
        "erp_warehouse_code": "F004",
        "loading_point": "2R04",
    },
    {
        "code": 2401005,
        "name": "ЛогЛаб Солнечногорск",
        "city": "Солнечногорск",
        "region": "Московская область",
        "type": "warehouse",
        "erp_plant_code": 2401,
        "erp_warehouse_code": "F005",
        "loading_point": "2R05",
    },
    {
        "code": 2401006,
        "name": "ЛогЛаб Краснодар",
        "city": "Краснодар",
        "region": "Краснодарский край",
        "type": "warehouse",
        "erp_plant_code": 2401,
        "erp_warehouse_code": "F006",
        "loading_point": "2R06",
    },
    {
        "code": 2401010,
        "name": "ЛогЛаб Екатеринбург",
        "city": "Екатеринбург",
        "region": "Свердловская область",
        "type": "warehouse",
        "erp_plant_code": 2401,
        "erp_warehouse_code": "F010",
        "loading_point": "2R10",
    },
    {
        "code": 2401011,
        "name": "ЛогЛаб Новосибирск",
        "city": "Новосибирск",
        "region": "Новосибирская область",
        "type": "warehouse",
        "erp_plant_code": 2401,
        "erp_warehouse_code": "F011",
        "loading_point": "2R11",
    },
    {
        "code": 2401015,
        "name": "ЛогЛаб Калининград",
        "city": "Калининград",
        "region": "Калининградская область",
        "type": "warehouse",
        "erp_plant_code": 2401,
        "erp_warehouse_code": "F015",
        "loading_point": "2R15",
    },
    {
        "code": 2401016,
        "name": "ЛогЛаб Ростов-на-Дону",
        "city": "Ростов-на-Дону",
        "region": "Ростовская область",
        "type": "warehouse",
        "erp_plant_code": 2401,
        "erp_warehouse_code": "F016",
        "loading_point": "2R16",
    },
    {
        "code": 2401017,
        "name": "ЛогЛаб Тюмень",
        "city": "Тюмень",
        "region": "Тюменская область",
        "type": "warehouse",
        "erp_plant_code": 2401,
        "erp_warehouse_code": "F017",
        "loading_point": "2R17",
    },
    {
        "code": 2401018,
        "name": "ЛогЛаб Иркутск",
        "city": "Иркутск",
        "region": "Иркутская область",
        "type": "warehouse",
        "erp_plant_code": 2401,
        "erp_warehouse_code": "F018",
        "loading_point": "2R18",
    },
    {
        "code": 2401025,
        "name": "ЛогЛаб Хабаровск",
        "city": "Хабаровск",
        "region": "Хабаровский край",
        "type": "warehouse",
        "erp_plant_code": 2401,
        "erp_warehouse_code": "F025",
        "loading_point": "2R25",
    },
]
